# Generated by Django 4.1.5 on 2023-01-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField()),
                ('points', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('student_id', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=200)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('events', models.ManyToManyField(blank=True, related_name='attended_events', to='CyRanch_Connect.event')),
            ],
        ),
    ]
