# Generated by Django 4.1.5 on 2023-01-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyRanch_Connect', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prize',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prize',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prize',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='prize',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
