# Generated by Django 4.1.5 on 2023-01-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CyRanch_Connect', '0006_student_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'get_latest_by': 'points'},
        ),
    ]
