# Generated by Django 4.1.5 on 2023-01-21 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyRanch_Connect', '0007_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
