# Generated by Django 4.1.5 on 2023-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyRanch_Connect', '0009_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='slug',
        ),
        migrations.AddField(
            model_name='prize',
            name='event_id',
            field=models.SlugField(null=True),
        ),
    ]
