# Generated by Django 4.1.5 on 2023-03-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CyRanch_Connect', '0010_remove_prize_slug_prize_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='slug',
            new_name='event_id',
        ),
    ]
