# Generated by Django 4.1.5 on 2023-03-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyRanch_Connect', '0011_rename_slug_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='token',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
