# Generated by Django 4.1.5 on 2023-03-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyRanch_Connect', '0012_event_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='token',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
