# Generated by Django 4.1.6 on 2023-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyRanch_Connect', '0015_alter_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
