# Generated by Django 4.1.6 on 2023-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyRanch_Connect', '0016_remove_prize_event_id_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
